import "./style.css"
import { Project, Task, isComplete, changePriority, rankTasks } from "./todos"
// const content = document.querySelector('#content')
// const child = document.createElement('span')
// child.textContent = 'Hello'

// content.appendChild(child)


const sleep = new Task('sleep', '9pm')
console.log(sleep.name)
console.log(sleep.dueDate)
sleep.changeDescription('I wanna sleep early')
console.log(sleep.description)
sleep.checkCompletion()
isComplete(sleep)
sleep.checkCompletion()
changePriority(sleep).raisePriority()
console.log(sleep.priority)

let sleepPriority = changePriority(sleep)
sleepPriority.lowerPriority()
sleepPriority.lowerPriority()
sleepPriority.lowerPriority()
sleepPriority.lowerPriority()
console.log(sleep.priority)
const eat = new Task('eat')
const gym = new Task('gym')
const shower = new Task('shower')
const work = new Task('work')
let eatPriority = changePriority(eat)
eatPriority.raisePriority()
eatPriority.raisePriority()
let gymPriority = changePriority(gym)
gymPriority.raisePriority()
gymPriority.raisePriority()
gymPriority.raisePriority()
let showerPriority = changePriority(shower)
showerPriority.raisePriority()
let workPriority = changePriority(work)
workPriority.raisePriority()
workPriority.raisePriority()
workPriority.raisePriority()
workPriority.raisePriority()
workPriority.raisePriority()
workPriority.raisePriority()
workPriority.raisePriority()
console.log(gym.priority)
console.log(shower.priority)
console.log(work.priority)
console.log(eat.priority)

const testTasks = new Project('test')
testTasks.addToArray(sleep)
testTasks.addToArray(gym)
testTasks.addToArray(eat)
testTasks.addToArray(shower)
testTasks.addToArray(work)

testTasks.showArray()
console.log(testTasks.array)
rankTasks(testTasks.array)